showcase_homepage:
    path:      /
    defaults:  { _controller: FlobFoundationDemoBundle:Demo:Showcase }

showcase_level1:
    path:      /level1/
    defaults:  { _controller: FlobFoundationDemoBundle:Demo:Showcase }

showcase_level2:
    path:      /level1/level2/
    defaults:  { _controller: FlobFoundationDemoBundle:Demo:Showcase }

theme_homepage:
    path:      /theme/
    defaults:  { _controller: FlobFoundationDemoBundle:Theme:Showcase }