showcase_homepage:
    path:      /
    defaults:  { _controller: FlorianBelhommeFoundationDemoBundle:Demo:Showcase }

showcase_level1:
    path:      /level1/
    defaults:  { _controller: FlorianBelhommeFoundationDemoBundle:Demo:Showcase }
    
showcase_level2:
    path:      /level1/level2/
    defaults:  { _controller: FlorianBelhommeFoundationDemoBundle:Demo:Showcase }